name: Deploy to NGINX
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem
          
      - name: Deploy files via RSYNC
        run: |
          rsync -avz --no-perms --no-owner --no-group --delete -e "ssh -i ~/.ssh/deploy_key.pem" ./ user@server:/var/www/html/
          ssh -i ~/.ssh/deploy_key.pem user@server "sudo chown -R www-data:www-data /var/www/html && sudo chmod -R 755 /var/www/html"
